const grade_levels = [
    { id: 'Kindergarden', text: 'Kindergarden' },
    { id: '1st', text: '1st' },
    { id: '2nd', text: '2nd' },
    { id: '3rd', text: '3rd' },
    { id: '4th', text: '4th' },
    { id: '5th', text: '5th' },
    { id: '6th', text: '6th' },
    { id: '7th', text: '7th' },
    { id: '8th', text: '8th' },
    { id: '9th', text: '9th' },
    { id: '10th', text: '10th' },
    { id: '11th', text: '11th' },
    { id: '12th', text: '12th' },
];